"""create Ride and Carpool models

Revision ID: 0a5980a44586
Revises: fc00097faa88
Create Date: 2025-10-25 07:54:31.279305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5980a44586'
down_revision = 'fc00097faa88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carpool_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carpool_id'], ['carpool.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride_riders',
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_carpool', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('carpool_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carpool', ['carpool_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carpool_id')
        batch_op.drop_column('allow_carpool')

    op.drop_table('ride_riders')
    op.drop_table('ride')
    op.drop_table('carpool')
    # ### end Alembic commands ###
