"""add invisible_multiopps to feed_order

Revision ID: 2014702b0eb4
Revises: 6356b4fc4408
Create Date: 2026-03-21 19:20:09.891039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2014702b0eb4'
down_revision = '6356b4fc4408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invisible_multiopps', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_order', schema=None) as batch_op:
        batch_op.drop_column('invisible_multiopps')

    # ### end Alembic commands ###
