"""added cascades

Revision ID: 4c3fab48e1d5
Revises: df69b8dd6e8b
Create Date: 2025-10-25 19:47:40.082870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3fab48e1d5'
down_revision = 'df69b8dd6e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carpool', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carpool_opportunity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'opportunity', ['opportunity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carpool', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('carpool_opportunity_id_fkey'), 'opportunity', ['opportunity_id'], ['id'])

    # ### end Alembic commands ###
