"""removed carpool_id from opp table

Revision ID: 5f39d37f4267
Revises: 0a5980a44586
Create Date: 2025-10-25 09:11:33.103900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f39d37f4267'
down_revision = '0a5980a44586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('opportunity_carpool_id_fkey'), type_='foreignkey')
        batch_op.drop_column('carpool_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carpool_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('opportunity_carpool_id_fkey'), 'carpool', ['carpool_id'], ['id'])

    # ### end Alembic commands ###
