"""added RideRider model, removed table

Revision ID: 6109b1f6ff46
Revises: 5f39d37f4267
Create Date: 2025-10-25 19:00:29.564970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6109b1f6ff46'
down_revision = '5f39d37f4267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('ride_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pickup_location',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_riders', schema=None) as batch_op:
        batch_op.alter_column('pickup_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ride_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
