"""create car model

Revision ID: 657a46dd747b
Revises: 6acf94e60cc6
Create Date: 2025-10-31 21:36:49.346173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657a46dd747b'
down_revision = '6acf94e60cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
