"""add heard_about field to user

Revision ID: 81521c40ca25
Revises: c392096031e2
Create Date: 2026-03-06 16:20:11.005661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81521c40ca25'
down_revision = 'c392096031e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heard_about', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('heard_about')

    # ### end Alembic commands ###
