"""Change multiopp delete behavior to SET NULL

Revision ID: c392096031e2
Revises: 9abf18dd9dbc
Create Date: 2026-01-25 17:10:42.400047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c392096031e2'
down_revision = '9abf18dd9dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('opportunity_multiopp_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'multi_opportunity', ['multiopp_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('opportunity_multiopp_id_fkey'), 'multi_opportunity', ['multiopp_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
