"""add_multiopp_model

Revision ID: cb09c83d0f8f
Revises: 4c3fab48e1d5
Create Date: 2025-11-04 01:49:53.448509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb09c83d0f8f'
down_revision = '4c3fab48e1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_opportunity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('causes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('nonprofit', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('host_org_name', sa.String(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.JSON(), nullable=True),
    sa.Column('host_org_id', sa.Integer(), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('week_frequency', sa.Integer(), nullable=True),
    sa.Column('week_recurrences', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['host_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiopp_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'multi_opportunity', ['multiopp_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('multiopp_id')

    op.drop_table('multi_opportunity')
    # ### end Alembic commands ###
