"""added notes field to riderider

Revision ID: ed28f24f8f09
Revises: 6924751a6519
Create Date: 2025-11-06 16:08:20.318238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed28f24f8f09'
down_revision = '6924751a6519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_riders', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
