"""Add CASCADE constraints for passive delete

Revision ID: f7786616235b
Revises: ed28f24f8f09
Create Date: 2026-01-23 14:31:55.473050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7786616235b'
down_revision = 'ed28f24f8f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('opportunity_multiopp_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'multi_opportunity', ['multiopp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ride_carpool_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'carpool', ['carpool_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ride_riders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ride_riders_ride_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ride', ['ride_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_riders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ride_riders_ride_id_fkey'), 'ride', ['ride_id'], ['id'])

    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ride_carpool_id_fkey'), 'carpool', ['carpool_id'], ['id'])

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('opportunity_multiopp_id_fkey'), 'multi_opportunity', ['multiopp_id'], ['id'])

    # ### end Alembic commands ###
