"""Add Waiver table

Revision ID: f7b61f73faeb
Revises: c8f73ecd751c
Create Date: 2025-10-13 16:13:11.747763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b61f73faeb'
down_revision = 'c8f73ecd751c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typed_name', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('checked_consent', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_friendship_accepted'))
        batch_op.drop_index(batch_op.f('idx_friendship_receiver'))
        batch_op.drop_index(batch_op.f('idx_friendship_requester'))

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_opportunity_date'))
        batch_op.drop_column('cause')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('user_opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_opportunity_opportunity_id'))
        batch_op.drop_index(batch_op.f('idx_user_opportunity_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_opportunity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_opportunity_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_opportunity_opportunity_id'), ['opportunity_id'], unique=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_opportunity_date'), ['date'], unique=False)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_friendship_requester'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_friendship_receiver'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_friendship_accepted'), ['accepted'], unique=False)

    op.drop_table('waiver')
    # ### end Alembic commands ###
