"""add new field carpool_waiver_signed to User

Revision ID: fc00097faa88
Revises: f7b61f73faeb
Create Date: 2025-10-13 20:56:39.717311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc00097faa88'
down_revision = 'f7b61f73faeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_friendship_accepted'))
        batch_op.drop_index(batch_op.f('idx_friendship_receiver'))
        batch_op.drop_index(batch_op.f('idx_friendship_requester'))

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_opportunity_date'))
        batch_op.drop_column('cause')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carpool_waiver_signed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_opportunity_opportunity_id'))
        batch_op.drop_index(batch_op.f('idx_user_opportunity_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_opportunity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_opportunity_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_opportunity_opportunity_id'), ['opportunity_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('carpool_waiver_signed')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_opportunity_date'), ['date'], unique=False)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_friendship_requester'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_friendship_receiver'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_friendship_accepted'), ['accepted'], unique=False)

    # ### end Alembic commands ###
